// import HeroBanner from '@/components/HeroBanner';
// import Wrapper from '@/components/Wrapper';

import Head from 'next/head';
import Header from '@/components/Header';
import HeroBanner from '@/components/HeroBanner';
import ProductCard from '@/components/ProductCard';
import HomePage from '@/sections/home';
import Footer from '@/components/Footer';
import About from '@/sections/about';
import Shop from '@/sections/shop';

export default function Home() {
	return (
		<>
			<Head>
				<title>Tu Cafe Gourmet</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='anonymous' />
			</Head>
			{/* { <Provider store={store}> */}
			<Header />
			<HomePage products={[]} />
			<About />
			<Shop />
			<Footer />
			{/* </Provider> } */}
		</>
	);
}
